/* =============================================
   ROUTES.JS
   The one place that decides where an article or tool lives.

   Every article gets its own real, static file:
     /blog/<id>.html     (stories + articles)
     /tools/<id>.html    (free tools)

   Those files are generated by `node scripts/build.mjs` and
   contain the full text in the raw HTML — nothing is fetched or
   assembled by JavaScript before a crawler can read it.

   No DOM access here on purpose: this file is imported by the
   browser scripts AND by the Node build script.
   ============================================= */

import { findItemById } from '../data/store.js';

export const SITE_URL = 'https://herdigitalplaybook.com';
export const ARTICLE_DIR = 'blog';
export const TOOL_DIR = 'tools';

// Fixed pages that belong in the sitemap. my-academy, certificate and
// verify are personal/utility pages and intentionally left out.
export const STATIC_PAGES = [
  '/',
  '/pages/about.html',
  '/pages/contact.html',
  '/pages/privacy.html',
  '/pages/terms.html',
  '/pages/playground.html',
  '/pages/start-here.html',
  '/pages/money-path.html',
  '/pages/game-room.html',
  '/pages/client-simulator.html',
  '/pages/templates.html',
  '/pages/glossary.html',
  '/pages/academy.html',
];

/** "blog/some-id.html" — no leading slash, for use with BASE. */
export function itemRelPath(item) {
  return `${item.type === 'tool' ? TOOL_DIR : ARTICLE_DIR}/${item.id}.html`;
}

/** "/blog/some-id.html" — root-absolute, for static HTML. */
export function itemPath(item) {
  return `/${itemRelPath(item)}`;
}

/** Same as itemPath, starting from an id. Falls back to /blog/. */
export function itemPathById(id) {
  const item = findItemById(id);
  return item ? itemPath(item) : `/${ARTICLE_DIR}/${id}.html`;
}

export function itemRelPathById(id) {
  return itemPathById(id).slice(1);
}
