/* =============================================
   ROUTES.JS
   The one place that decides where an article or tool lives.

   Every article gets its own real, static file:
     /blog/<id>.html     (stories + articles)
     /tools/<id>.html    (free tools)

   Those files are generated by `node scripts/build.mjs` and
   contain the full text in the raw HTML — nothing is fetched or
   assembled by JavaScript before a crawler can read it.

   No DOM access here on purpose: this file is imported by the
   browser scripts AND by the Node build script.
   ============================================= */

import { findItemById } from '../data/store.js';

export const SITE_URL = 'https://herdigitalplaybook.com';
export const ARTICLE_DIR = 'blog';
export const TOOL_DIR = 'tools';

// Fixed pages that belong in the sitemap. my-academy, certificate and
// verify are personal/utility pages and intentionally left out.
export const STATIC_PAGES = [
  '/',
  '/pages/about.html',
  '/pages/contact.html',
  '/pages/privacy.html',
  '/pages/terms.html',
  // Clean, shareable URL — Vercel rewrites this to join-our-girl-gang.html
  // (see scripts/build.mjs -> vercelConfig()) without changing the address
  // bar, so this is the URL that belongs in the sitemap, not the .html one.
  '/join-our-girl-gang',
  // TEMPORARILY LEFT OUT while the AdSense review is open (their content is
  // built in the browser, so the raw HTML is thin): /pages/playground.html,
  // start-here, money-path, game-room, client-simulator, templates, glossary,
  // academy. Also left out: /playbook-live and its 3 legal pages.
  // Put them back here once those pages have real text in the raw HTML.
];

/** "blog/some-id.html" — no leading slash, for use with BASE. */
export function itemRelPath(item) {
  return `${item.type === 'tool' ? TOOL_DIR : ARTICLE_DIR}/${item.id}.html`;
}

/**
 * The public URL of an item — root-absolute, for static HTML.
 * Items flagged `cleanUrl: true` in data/store.js live at a clean root path
 * ("/some-id", no folder, no ".html", no query string). The file on disk is
 * still blog/<id>.html; vercel.json rewrites /<id> to it (see build.mjs).
 */
export function itemPath(item) {
  return item.cleanUrl ? `/${item.id}` : `/${itemRelPath(item)}`;
}

/** Same as itemPath, starting from an id. Falls back to /blog/. */
export function itemPathById(id) {
  const item = findItemById(id);
  return item ? itemPath(item) : `/${ARTICLE_DIR}/${id}.html`;
}

export function itemRelPathById(id) {
  return itemPathById(id).slice(1);
}
