#!/usr/bin/env node
/* =============================================
   scripts/build.mjs
   Static build for Her Digital Playbook.

   WHY THIS EXISTS
   Google's crawlers (AdSense included) are not guaranteed to run
   your JavaScript, or to wait for it. The old setup sent an empty
   shell — <div id="article-content">Loading…</div> — and filled it
   in the browser from /pages/article.html?id=<slug>. A crawler that
   reads the raw HTML saw no article at all.

   WHAT THIS DOES
   Reads data/store.js and writes the finished pages to disk:

     /blog/<id>.html     one real file per story / article, with the
                         headline, every chapter heading and every
                         paragraph already inside the HTML
     /tools/<id>.html    one real file per free tool
     /index.html         header, hero, article cards, footer inlined
     /pages/*.html       header, nav, footer inlined
     /pages/article.html tiny legacy redirect for old ?id= links
     /sitemap.xml        every crawlable URL, new paths only
     /vercel.json        301 redirects from the old ?id= URLs

   The generated pages still load js/article.js — but only to add
   behaviour (XP, quizzes, checklists, tools). All the reading
   content is there without it.

   USAGE
     node scripts/build.mjs           rebuild everything
     node scripts/build.mjs --check   change nothing; exit 1 if any
                                      generated file is out of date

   Run it after every edit to data/store.js, components/*.html or
   sections/*.html, then commit the result. Needs Node 20.19+ / 22.7+
   (the project's .js files are ES modules without a package.json).
   ============================================= */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK_ONLY = process.argv.includes('--check');
const GENERATED_MARK = '<!-- generated by scripts/build.mjs — edit data/store.js, then re-run the build -->';

/* ---------- load the project's own modules ---------- */

async function load(rel) {
  return import(pathToFileURL(path.join(ROOT, rel)).href);
}

let store, routes, renderer;
try {
  store = await load('data/store.js');
  routes = await load('js/routes.js');
  renderer = await load('js/article-render.js');
} catch (err) {
  console.error('\n✖ Could not load the site modules.');
  console.error('  This project uses ES modules in plain .js files, which needs');
  console.error('  Node 20.19+ or 22.7+ (you have ' + process.version + ').\n');
  console.error(err);
  process.exit(1);
}

const { ALL_ITEMS, FEATURED_STORIES, LATEST_ARTICLES, FREE_TOOLS } = store;
const { SITE_URL, STATIC_PAGES, itemPath, itemRelPath } = routes;
const { renderArticleContent, esc, optimizeCloudinaryUrl } = renderer;

/* ---------- tiny file helpers ---------- */

const changed = [];
const written = new Set();

function abs(rel) { return path.join(ROOT, rel); }
function read(rel) { return fs.readFileSync(abs(rel), 'utf8'); }

function write(rel, content) {
  written.add(rel);
  const file = abs(rel);
  const before = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (before === content) return;
  changed.push(rel);
  if (CHECK_ONLY) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function must(str, from, to, label) {
  if (!str.includes(from)) {
    throw new Error(`${label}: expected to find ${JSON.stringify(from)} — has the template changed?`);
  }
  return str.replace(from, () => to); // function form: "$" in content is never special
}

/* ---------- shared chrome: header + nav, footer, popup ---------- */

const headerHtml = read('components/header.html')
  .replace('<div id="nav-placeholder"></div>', () => read('components/nav.html').trim())
  .trim();
const footerHtml = read('components/footer.html').trim();
const popupHtml = read('components/girlgang-popup.html').trim();

/**
 * Drops `content` where <div id="NAME-placeholder"></div> used to be, wrapped in
 * markers so the next build can find it and refresh it in place.
 */
function inject(html, name, content) {
  const wrapped = `<!--hdp:${name}-->\n${content}\n<!--/hdp:${name}-->`;
  const blockRe = new RegExp(`<!--hdp:${name}-->[\\s\\S]*?<!--/hdp:${name}-->`);
  const placeholder = `<div id="${name}-placeholder"></div>`;
  if (blockRe.test(html)) return html.replace(blockRe, () => wrapped);
  if (html.includes(placeholder)) return html.replace(placeholder, () => wrapped);
  return html;
}

function inlineChrome(html) {
  html = inject(html, 'header', headerHtml);
  html = inject(html, 'footer', footerHtml);
  html = inject(html, 'girlgang-popup', popupHtml);
  return html;
}

/* ---------- shared <head> pieces (copied from the existing pages) ---------- */

const GA = `<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NSGZ1LLL0D"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-NSGZ1LLL0D');
</script>`;

const ADSENSE = `<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9364889137165221"
     crossorigin="anonymous"></script>`;

const FONTS = `<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Caveat:wght;700&family=Plus+Jakarta+Sans:ital,wght,400;0,500;0,600;0,700;0,800;1,500&display=swap" rel="stylesheet">`;

const ICON = 'https://res.cloudinary.com/s9jk4ddk/image/upload/v1786286194/file_00000000bf7c821186b8c99e14d14dfa_j8vxfm.png';

const jsonForScript = (obj) => JSON.stringify(obj).replace(/</g, '\\u003c');

/* ---------- /blog/<id>.html and /tools/<id>.html ---------- */

function articlePage(item) {
  const isTool = item.type === 'tool';
  const canonical = `${SITE_URL}${itemPath(item)}`;
  const description = item.metaDescription || item.excerpt;
  const title = `${item.title} — Her Digital Playbook`;
  const { html, chapters, layoutClass } = renderArticleContent(item, ALL_ITEMS);

  const crumbs = [
    { name: 'Home', url: `${SITE_URL}/` },
    { name: isTool ? 'Free Tools' : 'Articles', url: `${SITE_URL}/#${isTool ? 'tools' : 'articles'}` },
    { name: item.title, url: canonical },
  ];

  const schema = [
    {
      '@context': 'https://schema.org',
      '@type': isTool ? 'WebPage' : 'Article',
      headline: item.title,
      name: item.title,
      description,
      image: [item.image],
      articleSection: item.category,
      inLanguage: 'en',
      mainEntityOfPage: { '@type': 'WebPage', '@id': canonical },
      author: { '@type': 'Organization', name: 'Her Digital Playbook', url: `${SITE_URL}/` },
      publisher: {
        '@type': 'Organization',
        name: 'Her Digital Playbook',
        url: `${SITE_URL}/`,
        logo: { '@type': 'ImageObject', url: ICON },
      },
    },
    {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: crumbs.map((c, i) => ({ '@type': 'ListItem', position: i + 1, name: c.name, item: c.url })),
    },
  ];

  const pageData = { id: item.id, type: item.type || 'article', chapters };

  let out = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
${GENERATED_MARK}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
${GA}
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${canonical}">
<meta name="robots" content="index, follow, max-image-preview:large">
<link rel="icon" type="image/png" href="${ICON}">
<link rel="apple-touch-icon" href="${ICON}">
<meta property="og:site_name" content="Her Digital Playbook">
<meta property="og:type" content="${isTool ? 'website' : 'article'}">
<meta property="og:title" content="${esc(item.title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:image" content="${esc(item.image)}">
<meta property="og:url" content="${canonical}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(item.title)}">
<meta name="twitter:description" content="${esc(description)}">
<meta name="twitter:image" content="${esc(item.image)}">
${FONTS}
<link rel="stylesheet" href="../css/variables.css">
<link rel="stylesheet" href="../css/style.css">
<link rel="stylesheet" href="../css/animations.css">
<link rel="stylesheet" href="../css/responsive.css">
${ADSENSE}
<script type="application/ld+json">${jsonForScript(schema)}</script>
</head>
<body>

<div id="header-placeholder"></div>

<main class="article-page">
  <div class="container${layoutClass ? ` ${layoutClass}` : ''}" id="article-content" data-prerendered="true">${html}</div>
</main>

<div id="footer-placeholder"></div>
<div id="girlgang-popup-placeholder"></div>

<script type="application/json" id="article-data">${jsonForScript(pageData)}</script>
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>
<script src="../js/supabase.js"></script>
<script type="module" src="../js/article.js"></script>
</body>
</html>
`;
  return inlineChrome(out);
}

/* ---------- homepage: cards + sections rendered into index.html ---------- */

const cardTemplates = read('components/card-template.html');
function templateMarkup(id) {
  const m = cardTemplates.match(new RegExp(`<template id="${id}">([\\s\\S]*?)</template>`));
  if (!m) throw new Error(`components/card-template.html: <template id="${id}"> not found`);
  return m[1].trim();
}
const STORY_TPL = templateMarkup('tpl-story-card');
const TOOL_TPL = templateMarkup('tpl-tool-card');

function storyCard(item) {
  const url = itemPath(item);
  const L = 'story card template';
  let h = STORY_TPL;
  h = must(h, '<a class="card-img-link" href="#">', `<a class="card-img-link" href="${url}">`, L);
  h = must(h, '<span class="card-category"></span>', `<span class="card-category">${esc(item.missionLabel || item.category)}</span>`, L);
  h = must(h, '<img src="" alt="">', `<img src="${esc(optimizeCloudinaryUrl(item.image, 700))}" alt="${esc(item.title)}" loading="lazy" decoding="async">`, L);
  h = must(h, '<h3 class="card-title"></h3>', `<h3 class="card-title">${esc(item.title)}</h3>`, L);
  h = must(h, '<p class="card-desc"></p>', `<p class="card-desc">${esc(item.excerpt)}</p>`, L);
  h = must(h, '<span class="read-time"></span>', `<span class="read-time">${esc(item.readTime || '')}</span>`, L);
  h = must(h, '<a class="read-more" href="#">', `<a class="read-more" href="${url}">`, L);
  return h;
}

function toolCard(item) {
  const url = itemPath(item);
  const L = 'tool card template';
  let h = TOOL_TPL;
  h = must(h, '<a class="card-img-link" href="#">', `<a class="card-img-link" href="${url}">`, L);
  h = must(h, '<img src="" alt="">', `<img src="${esc(optimizeCloudinaryUrl(item.image, 700))}" alt="${esc(item.title)}" loading="lazy" decoding="async">`, L);
  h = must(h, '<h3 class="card-title"></h3>', `<h3 class="card-title">${esc(item.title)}</h3>`, L);
  h = must(h, '<p class="card-desc"></p>', `<p class="card-desc">${esc(item.excerpt)}</p>`, L);
  h = must(h, '<a class="btn btn-tool" href="#">', `<a class="btn btn-tool" href="${url}">`, L);
  return h;
}

function sectionWithCards(file, gridId, cardsHtml) {
  const comment = '<!-- Cards injected by js/render.js from data/store.js -->';
  let h = read(file);
  h = must(h, comment, cardsHtml, file);
  h = must(h, `id="${gridId}">`, `id="${gridId}" data-prerendered="true">`, file);
  return h.trim();
}

function homepage() {
  let html = read('index.html');
  html = inject(html, 'header', headerHtml);
  html = inject(html, 'hero', read('sections/hero.html').trim());
  html = inject(html, 'featured', sectionWithCards('sections/featured-stories.html', 'featured-grid', FEATURED_STORIES.map(storyCard).join('\n')));
  html = inject(html, 'categories', read('sections/categories.html').trim());
  html = inject(html, 'latest', sectionWithCards('sections/latest-articles.html', 'latest-grid', LATEST_ARTICLES.map(storyCard).join('\n')));
  html = inject(html, 'tools', sectionWithCards('sections/free-tools.html', 'tools-grid', FREE_TOOLS.map(toolCard).join('\n')));
  html = inject(html, 'playground-teaser', read('sections/playground-teaser.html').trim());
  html = inject(html, 'academy-teaser', read('sections/academy-teaser.html').trim());
  html = inject(html, 'newsletter', read('sections/newsletter.html').trim());
  html = inject(html, 'footer', footerHtml);
  html = inject(html, 'girlgang-popup', popupHtml);
  // NOT inlined on purpose: the splash overlay (main.js only starts its
  // fade-out when it loads the splash itself) and the <template> card
  // shells js/render.js clones for the category filter.
  return html;
}

/* ---------- legacy redirect page: /pages/article.html?id=... ---------- */

function legacyRedirectPage() {
  const map = Object.fromEntries(ALL_ITEMS.map((i) => [i.id, itemPath(i)]));
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
${GENERATED_MARK}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex, follow">
<title>Redirecting — Her Digital Playbook</title>
<link rel="canonical" href="${SITE_URL}/">
<script>
  // Old links looked like /pages/article.html?id=<slug>. Every article now has
  // its own static page; send the reader there. (Vercel already 301s these on
  // the server — this is the fallback for anything that slips past.)
  (function () {
    var map = ${jsonForScript(map)};
    var id = new URLSearchParams(window.location.search).get('id');
    window.location.replace(map[id] || '/#articles');
  })();
</script>
</head>
<body>
<p>This page has moved. <a href="/#articles">Browse all articles</a>.</p>
</body>
</html>
`;
}

/* ---------- sitemap.xml ---------- */

function sitemap() {
  const urls = [
    ...STATIC_PAGES.map((p) => `${SITE_URL}${p}`),
    ...ALL_ITEMS.map((i) => `${SITE_URL}${itemPath(i)}`),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>\n    <loc>${u}</loc>\n  </url>`).join('\n')}
</urlset>
`;
}

/* ---------- vercel.json: 301 the old ?id= URLs ---------- */

function vercelConfig() {
  const cfg = JSON.parse(read('vercel.json'));
  const isLegacy = (r) => r.source === '/pages/article.html' || r.source === '/blog' || r.source === '/tools';
  const kept = (cfg.redirects || []).filter((r) => !isLegacy(r));
  const legacy = ALL_ITEMS.map((i) => ({
    source: '/pages/article.html',
    has: [{ type: 'query', key: 'id', value: i.id }],
    destination: itemPath(i),
    permanent: true,
  }));
  cfg.redirects = [
    ...kept,
    ...legacy,
    { source: '/blog', destination: '/#articles', permanent: false },
    { source: '/tools', destination: '/#tools', permanent: false },
  ];
  return JSON.stringify(cfg, null, 2) + '\n';
}

/* =============================================
   RUN
   ============================================= */

// 1. one static page per item
for (const item of ALL_ITEMS) {
  write(itemRelPath(item), articlePage(item));
}

// 2. remove pages for items that no longer exist in store.js
for (const dir of [routes.ARTICLE_DIR, routes.TOOL_DIR]) {
  if (!fs.existsSync(abs(dir))) continue;
  for (const f of fs.readdirSync(abs(dir))) {
    const rel = `${dir}/${f}`;
    if (!f.endsWith('.html') || written.has(rel)) continue;
    if (!read(rel).includes(GENERATED_MARK)) continue; // hand-written file — leave it alone
    changed.push(`${rel} (removed)`);
    if (!CHECK_ONLY) fs.unlinkSync(abs(rel));
  }
}

// 3. homepage + inner pages
write('index.html', homepage());

for (const f of fs.readdirSync(abs('pages')).filter((n) => n.endsWith('.html')).sort()) {
  if (f === 'article.html') continue;
  write(`pages/${f}`, inlineChrome(read(`pages/${f}`)));
}
write('pages/article.html', legacyRedirectPage());

// 4. sitemap + redirects
write('sitemap.xml', sitemap());
write('vercel.json', vercelConfig());

/* ---------- report ---------- */

const articles = ALL_ITEMS.filter((i) => i.type !== 'tool').length;
const tools = ALL_ITEMS.length - articles;
if (CHECK_ONLY) {
  if (changed.length) {
    console.error(`✖ ${changed.length} generated file(s) are out of date. Run: node scripts/build.mjs\n  ` + changed.join('\n  '));
    process.exit(1);
  }
  console.log('✔ All generated files are up to date.');
} else {
  console.log(`✔ Built ${articles} article pages → /${routes.ARTICLE_DIR}/  and  ${tools} tool pages → /${routes.TOOL_DIR}/`);
  console.log(`  ${changed.length} file(s) written${changed.length ? ':' : ' (nothing changed)'}`);
  if (changed.length && changed.length <= 40) console.log('  ' + changed.join('\n  '));
}
